apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::964594203602:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18WT9EO5RO173
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
    - rolearn: arn:aws:iam::964594203602:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-26T20:23:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "954"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d0415228-f59d-427d-bee9-ec97a9a97029
