apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::964594203602:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::964594203602:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-26T22:23:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "831"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1ff2df0a-438a-4d09-9694-8b68e71a5e80
